# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -ruleid {1}  -id {Synth 8-2306}  -suppress 
create_project -in_memory -part xc7k325tfbg676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/NewLand/Learn/Verilog/clock/project/misc/trunk/prj/dac.cache/wt [current_project]
set_property parent.project_path D:/NewLand/Learn/Verilog/clock/project/misc/trunk/prj/dac.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/NewLand/Learn/Verilog/clock/project/misc/trunk/prj/dac.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/NewLand/Learn/Verilog/clock/project/ad9783_dds/doc/coe/triangle_wave.coe
add_files -quiet D:/NewLand/Learn/Verilog/clock/project/misc/trunk/dcp/dds_16chl.dcp
set_property used_in_implementation false [get_files D:/NewLand/Learn/Verilog/clock/project/misc/trunk/dcp/dds_16chl.dcp]
add_files -quiet D:/NewLand/Learn/Verilog/clock/project/misc/trunk/dcp/ad9172_inf.dcp
set_property used_in_implementation false [get_files D:/NewLand/Learn/Verilog/clock/project/misc/trunk/dcp/ad9172_inf.dcp]
add_files -quiet D:/NewLand/Learn/Verilog/clock/project/misc/trunk/dcp/ad9783_inf.dcp
set_property used_in_implementation false [get_files D:/NewLand/Learn/Verilog/clock/project/misc/trunk/dcp/ad9783_inf.dcp]
add_files -quiet D:/NewLand/Learn/Verilog/clock/project/misc/trunk/dcp/ad_inf.dcp
set_property used_in_implementation false [get_files D:/NewLand/Learn/Verilog/clock/project/misc/trunk/dcp/ad_inf.dcp]
add_files -quiet d:/NewLand/Learn/Verilog/clock/project/misc/trunk/ip/vio_2/vio_2.dcp
set_property used_in_implementation false [get_files d:/NewLand/Learn/Verilog/clock/project/misc/trunk/ip/vio_2/vio_2.dcp]
add_files -quiet d:/NewLand/Learn/Verilog/clock/project/misc/trunk/ip/vio_dds_1/vio_dds_1.dcp
set_property used_in_implementation false [get_files d:/NewLand/Learn/Verilog/clock/project/misc/trunk/ip/vio_dds_1/vio_dds_1.dcp]
add_files -quiet d:/NewLand/Learn/Verilog/clock/project/misc/trunk/prj/dac.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files d:/NewLand/Learn/Verilog/clock/project/misc/trunk/prj/dac.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.dcp]
add_files -quiet D:/NewLand/Learn/Verilog/clock/project/misc/trunk/prj/dac.srcs/sources_1/ip/vio_dac_vc_dds/vio_dac_vc_dds.dcp
set_property used_in_implementation false [get_files D:/NewLand/Learn/Verilog/clock/project/misc/trunk/prj/dac.srcs/sources_1/ip/vio_dac_vc_dds/vio_dac_vc_dds.dcp]
read_verilog -library xil_defaultlib {
  D:/NewLand/Learn/Verilog/clock/project/misc/trunk/src/dds/value_att_round.v
  D:/NewLand/Learn/Verilog/clock/project/misc/trunk/src/dds/dds_for_7_series_iq.v
  D:/NewLand/Learn/Verilog/clock/project/misc/trunk/src/top/freq_calc.v
  D:/NewLand/Learn/Verilog/clock/project/misc/trunk/src/clock/clock_module.v
  D:/NewLand/Learn/Verilog/clock/project/misc/trunk/src/top/top.v
  D:/NewLand/Learn/Verilog/clock/project/misc/trunk/src/clock/clk_wiz_0.v
  D:/NewLand/Learn/Verilog/clock/project/misc/trunk/src/clock/clk_wiz_0_clk_wiz.v
  D:/NewLand/Learn/Verilog/clock/project/misc/trunk/src/dds/triangle_wave.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/NewLand/Learn/Verilog/clock/project/misc/trunk/xdc/common.xdc
set_property used_in_implementation false [get_files D:/NewLand/Learn/Verilog/clock/project/misc/trunk/xdc/common.xdc]

read_xdc D:/NewLand/Learn/Verilog/clock/project/misc/trunk/xdc/debug.xdc
set_property used_in_implementation false [get_files D:/NewLand/Learn/Verilog/clock/project/misc/trunk/xdc/debug.xdc]

read_xdc D:/NewLand/Learn/Verilog/clock/project/misc/trunk/xdc/ad9783.xdc
set_property used_in_implementation false [get_files D:/NewLand/Learn/Verilog/clock/project/misc/trunk/xdc/ad9783.xdc]

read_xdc D:/NewLand/Learn/Verilog/clock/project/misc/trunk/xdc/hqnuo_ck_cptatomicclk_adc.xdc
set_property used_in_implementation false [get_files D:/NewLand/Learn/Verilog/clock/project/misc/trunk/xdc/hqnuo_ck_cptatomicclk_adc.xdc]

read_xdc D:/NewLand/Learn/Verilog/clock/project/misc/trunk/xdc/ad9172.xdc
set_property used_in_implementation false [get_files D:/NewLand/Learn/Verilog/clock/project/misc/trunk/xdc/ad9172.xdc]

read_xdc D:/NewLand/Learn/Verilog/clock/project/misc/trunk/xdc/timing.xdc
set_property used_in_implementation false [get_files D:/NewLand/Learn/Verilog/clock/project/misc/trunk/xdc/timing.xdc]


synth_design -top top -part xc7k325tfbg676-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
