set_property PACKAGE_PIN P1 [get_ports {iob_ad9172_txn[0]}]
set_property PACKAGE_PIN P2 [get_ports {iob_ad9172_txp[0]}]
set_property PACKAGE_PIN M1 [get_ports {iob_ad9172_txn[1]}]
set_property PACKAGE_PIN M2 [get_ports {iob_ad9172_txp[1]}]
set_property PACKAGE_PIN K1 [get_ports {iob_ad9172_txn[2]}]
set_property PACKAGE_PIN K2 [get_ports {iob_ad9172_txp[2]}]
set_property PACKAGE_PIN H1 [get_ports {iob_ad9172_txn[3]}]
set_property PACKAGE_PIN H2 [get_ports {iob_ad9172_txp[3]}]
set_property PACKAGE_PIN F1 [get_ports {iob_ad9172_txn[4]}]
set_property PACKAGE_PIN F2 [get_ports {iob_ad9172_txp[4]}]
set_property PACKAGE_PIN D1 [get_ports {iob_ad9172_txn[5]}]
set_property PACKAGE_PIN D2 [get_ports {iob_ad9172_txp[5]}]
set_property PACKAGE_PIN B1 [get_ports {iob_ad9172_txn[6]}]
set_property PACKAGE_PIN B2 [get_ports {iob_ad9172_txp[6]}]
set_property PACKAGE_PIN A3 [get_ports {iob_ad9172_txn[7]}]
set_property PACKAGE_PIN A4 [get_ports {iob_ad9172_txp[7]}]

set_property PACKAGE_PIN U2 [get_ports {iob_ad9172_sync204_p[0]}]
set_property PACKAGE_PIN U1 [get_ports {iob_ad9172_sync204_n[0]}]
set_property PACKAGE_PIN U6 [get_ports {iob_ad9172_sync204_p[1]}]
set_property PACKAGE_PIN U5 [get_ports {iob_ad9172_sync204_n[1]}]

set_property PACKAGE_PIN Y1 [get_ports iob_ad9172_rst_n]
set_property PACKAGE_PIN W3 [get_ports {iob_ad9172_tx_en[0]}]
set_property PACKAGE_PIN V4 [get_ports {iob_ad9172_tx_en[1]}]
set_property PACKAGE_PIN V1 [get_ports iob_ad9172_sck]
set_property PACKAGE_PIN W1 [get_ports iob_ad9172_sda]
set_property PACKAGE_PIN V2 [get_ports iob_ad9172_csb]


set_property PACKAGE_PIN K6 [get_ports iob_refclk_p]
set_property PACKAGE_PIN K5 [get_ports iob_refclk_n]

set_property PACKAGE_PIN AC4 [get_ports iob_sysref_p]
set_property PACKAGE_PIN AC3 [get_ports iob_sysref_n]

set_property PACKAGE_PIN AA4 [get_ports iob_glblclk_p]
set_property PACKAGE_PIN AB4 [get_ports iob_glblclk_n]

set_property PACKAGE_PIN V23 [get_ports iob_lmk_csb]
set_property PACKAGE_PIN V22 [get_ports iob_lmk_sck]
set_property PACKAGE_PIN U22 [get_ports iob_lmk_sdi]
set_property PACKAGE_PIN U21 [get_ports iob_lmk_sdo]
set_property PACKAGE_PIN Y20 [get_ports iob_lmk_status]

set_property IOSTANDARD LVDS [get_ports {iob_ad9172_sync204_*[0]}]
set_property IOSTANDARD LVDS [get_ports {iob_ad9172_sync204_*[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports iob_ad9172_rst_n]
set_property IOSTANDARD LVCMOS18 [get_ports {iob_ad9172_tx_en[*]}]
set_property IOSTANDARD LVCMOS18 [get_ports iob_ad9172_sck]
set_property IOSTANDARD LVCMOS18 [get_ports iob_ad9172_sda]
set_property IOSTANDARD LVCMOS18 [get_ports iob_ad9172_csb]
set_property IOSTANDARD LVDS [get_ports iob_sysref_*]
set_property IOSTANDARD LVDS [get_ports iob_glblclk_*]
set_property IOSTANDARD LVCMOS33 [get_ports iob_lmk_csb]
set_property IOSTANDARD LVCMOS33 [get_ports iob_lmk_sck]
set_property IOSTANDARD LVCMOS33 [get_ports iob_lmk_sdi]
set_property IOSTANDARD LVCMOS33 [get_ports iob_lmk_sdo]
set_property IOSTANDARD LVCMOS33 [get_ports iob_lmk_status]

create_clock -period 10.000 -name gt_refclk [get_ports iob_refclk_p]
create_clock -period 10.000 -name glblclk [get_ports iob_glblclk_p]

